name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3
      - name: cd directory
        run: cd Calculator-package
      - name: Build
        run: swift build -v
      - name: Run tests
        run: swift test
