name: Testing
on: push

jobs:
  test:
    name: Testing Swift Package and iOS app
    runs-on: macOS-11
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1
      - name: Force XCode 11.3
        run: |
          sudo xcode-select --switch /Library/Developer/CommandLineTools 
          sudo xcode-select --switch /Applications/Xcode_12.5.app
      - name: Testing Swift package
        run: sudo exec ./.github/test_swift_package.sh
      - name: Testing iOS app
        run: sudo exec ./.github/test_app.sh
